### ISSUE TITLE
Add a new function to get daily data from buffett-code API

### ISSUE THREAD

**Issue by shoe116** [BuffettCode/buffett-code-api-client-google-spreadsheet#13]
## What
- support endpoint [get_api_v2_daily](https://docs.buffett-code.com/#/default/get_api_v2_daily)

## Design
1. Split functions by end points,
- `BCODE_QUARTER(ticker, fy, fq, name)`
- `BCODE_DAILY(ticker, date, name)`

and make wrapper, `BCODE` and change interface of it.
- `BCODE (ticker, fy, fq, name)` => `BCODE(type, ticker, arg1, arg2, arg3)`.

**Comment by akiomik** [comment]
- `BCODE_INDICATOR(ticker, name)`も作る
